### PR TITLE
Add restful api

### PR DESCRIPTION
**Pull request by wuchang0201**
add restful api show summary

### CODE REVIEW

**Review by d3c3mber — COMMENTED** [review]
can you please squash the commits into one? thanks @wuchang0201

**Comment by larryck** [comment]
Hi @wuchang0201 , we have a new branch container-lifecyle-summary for this feature, cloud you move this pr to that branch ?

**Comment by wuchang0201** [comment]
> can you please squash the commits into one? thanks @wuchang0201

ok

**Comment by wuchang0201** [comment]
> Hi @wuchang0201 , we have a new branch container-lifecyle-summary for this feature, cloud you move this pr to that branch ?

got it

**Comment by wuchang0201** [comment]
move to  new branch

**Pull request closed without merging**
