### PR TITLE
rename delete-es to purge-es in cronjob

### PR DESCRIPTION
**Pull request by ponsAoki**
Renamed delete-es to purge-es in cronjob.
I am trying to resolve the following issue.
- https://github.com/alipay/container-observability-service/issues/121

### CODE REVIEW

**Review by d3c3mber — COMMENTED** [review]
Thanks @ponsAoki , besides the name of the CronJob, there's also a configmap called "delete-index-script", can you please help to rename this configmap as well

**Comment by ponsAoki** [comment]
@d3c3mber 
[rename ConfigMap delete-index-script to purge-index-script](https://github.com/alipay/container-observability-service/pull/126/commits/e25f922e2822f41a869610cffdaa236df5b802fe)
I also changed the name of ConfigMap from delete-index-script to purge-index-script!

**Review by d3c3mber — APPROVED** [review]
thanks @ponsAoki, lgtm

**Review by liubin — APPROVED** [review]

**Comment by hnhbwlp** [comment]
lgtm

**Review by hnhbwlp — APPROVED** [review]

**Pull request merged**
