### PR TITLE
add lunettes-logo

### PR DESCRIPTION
**Pull request by larryck**
Add the lunettes-logo to readme files

### CODE REVIEW

**Comment by larryck** [comment]
@hnhbwlp  @d3c3mber  cloud you take a look at this PR ?

**Review by d3c3mber — APPROVED** [review]
LGTM

**Comment by hnhbwlp** [comment]
/LGTM
This is a very cool design.

**Review by hnhbwlp — APPROVED** [review]
/LGTM
This is a very cool design.

**Pull request merged**
