### PR TITLE
Fix the bug that json format is incorrect and incomplete retrieval

### LINKED ISSUE #108: Yaml panel‘s json format is incorrect
### There's no existing/similar bug report.

- [X] I have searched the existing issues

### Describe the bug:

1.The json data displayed on yaml panel has wrong format；
2.Use The search command（ctrl/command+F）to check json, the obtained result will not include all matching content

### Expected behavior:

1.The json data displayed on yaml panel should has correct format；
2.The obtained result should include all matching content

### Additional

_No response_

### Lunettes version

_No response_

### Kubernetes version

_No response_

### PR DESCRIPTION
**Pull request by LLKCoder**
## Description
1.Fix the bug that yaml panel's json format is incorrect.
before:
F75C2F2A-434F-4B38-B404-8CB8BAABE3CF

after:
DBF400E2-2DB2-4522-870C-36A7B5D1269C

2.Use The search command（ctrl/command+F）to check json, the obtained result will include all matching content
C83354BC-7ED1-4CE4-8F94-85972F1C1AFA

## RelatedIssues
Closed #108

### CODE REVIEW

**Review by d3c3mber — APPROVED** [review]

**Comment by d3c3mber** [comment]
the e2e test is failing, can you please take a look @LLKCoder

**Comment by d3c3mber** [comment]
related link: https://bugs.launchpad.net/bugs/cve/2024-3094

**Review by d3c3mber — APPROVED** [review]

**Comment by d3c3mber** [comment]
related link: https://answers.launchpad.net/ubuntu/+question/710903

**Comment by d3c3mber** [comment]
e2e is working now

**Comment by d3c3mber** [comment]
lgtm

**Review by hnhbwlp — APPROVED** [review]
LGTM

**Pull request merged**
