### PR TITLE
Add the TKP feature item.

### PR DESCRIPTION
**Pull request by meetwangdk**
add the TKP feature item.
## Commit Summary
- Implemented the TKP (Managed Pod) API functionality.
- Developed the feature to view the topology diagram during the TKP management process.
- Completed the API development to display the current phase of the TKP.

### CODE REVIEW

**Comment by hnhbwlp** [comment]
Please describe the core capabilities of this feature.

**Comment by meetwangdk** [comment]
Have been updated

**Review by hnhbwlp — APPROVED** [review]
lgtm

**Review by d3c3mber — COMMENTED** [review]
There are conflicts in files, can you please help resolve them? thanks

**Review by d3c3mber — APPROVED** [review]

**Review by hnhbwlp — APPROVED** [review]
lgtm

**Pull request merged**
